[build-system]
requires = ["setuptools>=65.0.0", "wheel>=0.37.0"]
build-backend = "setuptools.build_meta"

[project]
name = "intellisearch"
version = "1.0.0"
requires-python = ">=3.11,<3.12"
description = "IntelliSearch - Intelligent Information Retrieval System"

[tool.setuptools]
py-modules = []