[global]
# Development mode for faster reloads
developmentMode = false

[server]
# Server settings optimized for cloud deployment
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

# Cloud deployment settings
headless = true
runOnSave = false
allowRunOnSave = false
fileWatcherType = "auto"

# Performance optimization
enableWebsocketCompression = true

[browser]
# Browser settings for cloud deployment
serverAddress = "0.0.0.0"
gatherUsageStats = false
serverPort = 8501

[theme]
# Dark theme optimized for Safari rendering
primaryColor = "#00ff88"
backgroundColor = "#0f0f23"
secondaryBackgroundColor = "#1a1a3a"
textColor = "#e1e8ed"
font = "sans serif"

[client]
# Safari performance optimizations
toolbarMode = "auto"
showSidebarNavigation = true