[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00ff88"
backgroundColor = "#0f0f1e"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#e1e8ed"

# Timeout settings for Streamlit Cloud
[runner]
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = false

# Memory optimization
[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

# Performance settings
[client]
toolbarMode = "minimal"